### ISSUE TITLE
NameError: uninitialized constant WordCountAnalyzer::Hyperlink::URI

### ISSUE THREAD

**Issue by thiensubs** [diasks2/word_count_analyzer#1]
After i install gem, i'm using simple default example in IRB with require 'word_count_analyzer'

text = "This string has a date: Monday, November 3rd, 2011. I was thinking... it also shouldn't have too many contractions, maybe 4. <html> Some HTML and a hyphenated-word</html>. Don't count stray punctuation ? ? ? Please visit the ____________ ------------ ........ go-to site: https://www.example-site.com today. Let's add a list 1. item a 2. item b 3. item c. Now let's add he/she/it or a c:\Users\john. 2/15/2012 is the date! { HYPERLINK 'http://www.hello.com' }"
WordCountAnalyzer::Analyzer.new(text: text).analyze
And I got this error message bellow:
NameError: uninitialized constant WordCountAnalyzer::Hyperlink::URI
    from /home/thiensubs/.rvm/gems/ruby-2.2.0/gems/word_count_analyzer-0.0.12/lib/word_count_analyzer/hyperlink.rb:14:in `hyperlink?'
    from /home/thiensubs/.rvm/gems/ruby-2.2.0/gems/word_count_analyzer-0.0.12/lib/word_count_analyzer/hyphenated_word.rb:12:in`hyphenated_word?'
    from /home/thiensubs/.rvm/gems/ruby-2.2.0/gems/word_count_analyzer-0.0.12/lib/word_count_analyzer/analyzer.rb:15:in `block in analyze'
    from /home/thiensubs/.rvm/gems/ruby-2.2.0/gems/word_count_analyzer-0.0.12/lib/word_count_analyzer/analyzer.rb:13:in`each'
    from /home/thiensubs/.rvm/gems/ruby-2.2.0/gems/word_count_analyzer-0.0.12/lib/word_count_analyzer/analyzer.rb:13:in `each_with_index'
    from /home/thiensubs/.rvm/gems/ruby-2.2.0/gems/word_count_analyzer-0.0.12/lib/word_count_analyzer/analyzer.rb:13:in`analyze'
    from (irb):13
    from /home/thiensubs/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
Please check it.

**Comment by diasks2** [comment]
Thanks for bringing this to my attention. Sorry about the error. It should now be fixed in the [latest release](https://github.com/diasks2/word_count_analyzer/commit/f15db01a53f20babc2432d15920e69216b4d3c68) (0.0.13). Please let me know if you still encounter the issue.
